-- Limpiar tablas (por si acaso no es create-drop)
DELETE FROM frases;
DELETE FROM categorias;
DELETE FROM autores;
DELETE FROM usuarios;

-- Usuarios Reales
-- admin / admin (hash generated by app)
INSERT INTO usuarios (username, password, role) VALUES ('admin', '$2a$10$7BTfg2KXkc5.PNFG42nJOOgmNiSBfT.rbzTtriUICxW7tf4KKnLpS', 'ADMIN');
-- user / admin
INSERT INTO usuarios (username, password, role) VALUES ('user', '$2a$10$7BTfg2KXkc5.PNFG42nJOOgmNiSBfT.rbzTtriUICxW7tf4KKnLpS', 'STANDARD');

-- Categorias
INSERT INTO categorias (nombre) VALUES ('Filosofía');
INSERT INTO categorias (nombre) VALUES ('Ciencia');
INSERT INTO categorias (nombre) VALUES ('Literatura');

-- Autores
INSERT INTO autores (nombre, anio_nacimiento, anio_fallecimiento, profesion) VALUES ('Albert Einstein', 1879, 1955, 'Físico');
INSERT INTO autores (nombre, anio_nacimiento, anio_fallecimiento, profesion) VALUES ('René Descartes', 1596, 1650, 'Filósofo');
INSERT INTO autores (nombre, anio_nacimiento, anio_fallecimiento, profesion) VALUES ('Miguel de Cervantes', 1547, 1616, 'Escritor');
INSERT INTO autores (nombre, anio_nacimiento, anio_fallecimiento, profesion) VALUES ('Marie Curie', 1867, 1934, 'Científica');
INSERT INTO autores (nombre, anio_nacimiento, anio_fallecimiento, profesion) VALUES ('Aristóteles', -384, -322, 'Filósofo');
INSERT INTO autores (nombre, anio_nacimiento, anio_fallecimiento, profesion) VALUES ('Isaac Newton', 1643, 1727, 'Físico');

-- Frases
-- Frases de ejemplo

INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('Pienso, luego existo', '2026-02-14', (SELECT id FROM autores WHERE nombre = 'René Descartes'), (SELECT id FROM categorias WHERE nombre = 'Filosofía'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('La imaginación es más importante que el conocimiento', '2026-02-15', (SELECT id FROM autores WHERE nombre = 'Albert Einstein'), (SELECT id FROM categorias WHERE nombre = 'Ciencia'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('En un lugar de la Mancha...', '2026-02-16', (SELECT id FROM autores WHERE nombre = 'Miguel de Cervantes'), (SELECT id FROM categorias WHERE nombre = 'Literatura'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('Nada en la vida es para ser temido, es solo para ser comprendido', '2026-02-17', (SELECT id FROM autores WHERE nombre = 'Marie Curie'), (SELECT id FROM categorias WHERE nombre = 'Ciencia'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('La amistad es un alma que habita en dos cuerpos', '2026-02-18', (SELECT id FROM autores WHERE nombre = 'Aristóteles'), (SELECT id FROM categorias WHERE nombre = 'Filosofía'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('Lo que sabemos es una gota de agua; lo que ignoramos es el océano', '2026-02-19', (SELECT id FROM autores WHERE nombre = 'Isaac Newton'), (SELECT id FROM categorias WHERE nombre = 'Ciencia'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('Vivir sin filosofar es, propiamente, tener los ojos cerrados', '2026-02-20', (SELECT id FROM autores WHERE nombre = 'René Descartes'), (SELECT id FROM categorias WHERE nombre = 'Filosofía'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('El misterio es la cosa más bonita que podemos experimentar', '2026-02-21', (SELECT id FROM autores WHERE nombre = 'Albert Einstein'), (SELECT id FROM categorias WHERE nombre = 'Ciencia'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('El que lee mucho y anda mucho, ve mucho y sabe mucho', '2026-02-22', (SELECT id FROM autores WHERE nombre = 'Miguel de Cervantes'), (SELECT id FROM categorias WHERE nombre = 'Literatura'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('Mejor es una gota de ciencia que un mar de riquezas', '2026-02-23', (SELECT id FROM autores WHERE nombre = 'Marie Curie'), (SELECT id FROM categorias WHERE nombre = 'Ciencia')); -- Nota: cita aproximada o atribuida
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('La inteligencia consiste no solo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica', '2026-02-24', (SELECT id FROM autores WHERE nombre = 'Aristóteles'), (SELECT id FROM categorias WHERE nombre = 'Filosofía'));
INSERT INTO frases (texto, fecha_programada, autor_id, categoria_id) VALUES ('Si he visto más lejos es porque estoy sentado sobre los hombros de gigantes', '2026-02-25', (SELECT id FROM autores WHERE nombre = 'Isaac Newton'), (SELECT id FROM categorias WHERE nombre = 'Ciencia'));
